# Generated by Django 5.2 on 2025-05-02 16:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_date', models.DateField(default=django.utils.timezone.now)),
                ('ticket_code', models.CharField(editable=False, max_length=10, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('general', 'General'), ('vip', 'VIP')], max_length=10)),
            ],
        ),
    ]
