name: CD

# Este workflow se ejecuta cuando se crea una release
# Depende de que la Integración Continua haya pasado
on:
  release:
    types: [published]
  push:
    branches:
      - main


jobs:
  # Verificar que CI pasó en la rama main antes de hacer deploy
  check-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check if CI passed on main
        uses: actions/github-script@v7
        with:
          script: |
            // Obtener el último workflow run de CI en main
            const { data: workflows } = await github.rest.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'ci.yml',
              branch: 'main',
              status: 'completed',
              per_page: 1
            });
            
            if (workflows.workflow_runs.length === 0) {
              core.setFailed('No se encontraron ejecuciones de CI en main');
              return;
            }
            
            const lastRun = workflows.workflow_runs[0];
            if (lastRun.conclusion !== 'success') {
              core.setFailed(`El último CI en main falló: ${lastRun.conclusion}`);
              return;
            }
            
            console.log('✅ CI pasó exitosamente en main');

  # Deploy 
  deploy:
    name: Deploy
    needs: check-ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Get the date
        run: echo "date=$(date '+%Y%m%d%H%M%S')" >> $GITHUB_ENV
        
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/eventhub-app:latest,${{ secrets.DOCKERHUB_USERNAME }}/eventhub-app:${{ env.date }}
          
      - name: Deploy to Render
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK_URL }}